# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_rmgig1 <- function(aux_Sigma, lambda, Psi, Gamma) {
    .Call(`_bvarNWish_do_rmgig1`, aux_Sigma, lambda, Psi, Gamma)
}

do_rwishart <- function(Sigma, df) {
    .Call(`_bvarNWish_do_rwishart`, Sigma, df)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bvarNWish_RcppExport_registerCCallable`)
})
